import dynamic from "next/dynamic";
import TopNavigation from "./components/TopNavigation";
import "./globals.css";

export const metadata = {
  title: "YouTube",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const SideNavigation = dynamic(() => import("./components/SideNavigation"), {
    ssr: false,
  });

  return (
    <html lang="en">
      <body className="bg-zinc-900 text-zinc-200">
        <div className="flex h-screen w-screen flex-col">
          <TopNavigation />
          <div className="flex flex-1">
            <SideNavigation />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
